### ISSUE TITLE
README describes tutorial but source is TodoMVC

### ISSUE THREAD

**Issue by octref** [Microsoft/TypeScript-Vue-Starter#1]
This is really confusing. @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
This is @bowdenk7's fault for picking up the wrong repo: https://github.com/DanielRosenwasser/typescript-vue-tutorial

**Comment by bowdenk7** [comment]
Oh no! Really sorry about the confusion. I'll get this fixed ASAP

**Comment by DanielRosenwasser** [comment]
Should be fixed now. Thanks @octref!
