### ISSUE TITLE
How do I declare a field in 'data' of type 'any'?

### ISSUE THREAD

**Issue by cdllqos** [Microsoft/TypeScript-Vue-Starter#12]
in the .vue file, we use ':' assign data to variable, how could we define it's type like any,object

**Comment by DanielRosenwasser** [comment]
Could you give an example of what you'd like to write?

**Comment by cdllqos** [comment]
Maybe I'd like to writre:
`data {
return{
msg:any="hello DanielRosenwasser"
}
}`

**Comment by DanielRosenwasser** [comment]
Gotcha - I'd say the closest thing you could do is something like the folllowing:

```ts
Vue.extend({
  data: {
    msg: "hello to you too cdllqos!" as any
  }
})
```

You can shorten it down to

```ts
Vue.extend({
  data: {
    msg: null as any
  }
})
```

or

```ts
Vue.extend({
  data: {
    msg: undefined as any
  }
})
```

**Comment by cdllqos** [comment]
That counld done in this version? I'll try it. Thank U :)
