### ISSUE TITLE
<script lang='ts'> doesn't give opportunity to see all warnings and errors highlights  in ".vue" files.

### ISSUE THREAD

**Issue by CodeLookBook** [Microsoft/TypeScript-Vue-Starter#15]
For example:
Look of the code in ".vue" file (IDE: phpStorm).
![image](https://user-images.githubusercontent.com/12842434/27513894-3591a4e4-5981-11e7-8aef-d4ec41bffe79.png)
At the same time, console message is correct.
![image](https://user-images.githubusercontent.com/12842434/27513928-1ebd3f7a-5982-11e7-96f7-d0a39de42c2e.png)

Is that a problem of phpStorm?

**Comment by Zzzen** [comment]
Yes, it is.
![vue-ts-issue](https://user-images.githubusercontent.com/6630042/28019346-4127e924-65b3-11e7-8744-d79a061be4e0.png)

**Comment by danielding** [comment]
@Zzzen  how did you make tslint run well? 
请问怎么弄出来提示的？我试了不行。

**Comment by Zzzen** [comment]
下载这个仓库，安装好依赖就可以了。你确定使用的是最新版的tsc和vscode?@danielding

**Comment by danielding** [comment]
@Zzzen  试了，不行啊

**Comment by CodeLookBook** [comment]
What about English ?))

**Comment by peterchealse** [comment]
seperate the ts from vue file works, just write a ts file

**Comment by Zzzen** [comment]
Are you using the lastest vscode and tsc? I just downloaded this repo and everything worked fine @CodeLookBook

**Comment by DanielRosenwasser** [comment]
Should work if you're using Vetur.

**Comment by wuservices** [comment]
As for WebStorm, it looks like code within a SFC in `<script lang="ts">` doesn't really get the TypeScript treatment due to https://youtrack.jetbrains.com/issue/WEB-30807. Please vote there if you (like me) want that and arrived here trying to make that work.

**Comment by DanielRosenwasser** [comment]
Thanks for linking to that @wuservices!

I encourage other WebStorm users to surface feedback there.

Google Translate: 我鼓励其他WebStorm用户在那里提供反馈。
