### ISSUE TITLE
Can't load vue from webpack alias

### ISSUE THREAD

**Issue by herozhou** [Microsoft/TypeScript-Vue-Starter#25]
I cant get vue 'vue/types/index'  from  like this,
```
//main.ts 

import vue from 'vue'
```

But I want to use some vue plugin ,so I have to use vue from 'vue/dist/vue.esm.js'  
.Not  from 'vue/types/index'。I add webpack alias but it doesn't work.
![image](https://user-images.githubusercontent.com/16045604/31022571-cc3f860e-a4fe-11e7-9f5a-38dd19381e3c.png)

![image](https://user-images.githubusercontent.com/16045604/31022689-37e3bbdc-a4ff-11e7-9a3b-60393a634d66.png)

How cant I use both vue (js and ts) in my project ?

**Comment by herozhou** [comment]
and some error like this 

![image](https://user-images.githubusercontent.com/16045604/31023201-be13d402-a500-11e7-83f7-d72face33bee.png)

**Comment by DanielRosenwasser** [comment]
Sorry about the delay here; I bellieve you need to use `allowSyntheticDefaultImports` for this to work.
