### ISSUE TITLE
识别props的数据类型全部为any，是否应该改下？

### ISSUE THREAD

**Issue by yangdan8** [Microsoft/TypeScript-Vue-Starter#26]
props: {
            name: String,
            initialEnthusiasm: Number
        },

**Comment by DanielRosenwasser** [comment]
Sorry, unfortunately I won't be able to answer questions in languages other than English.

I can be more explicit on props inference now that Vue 2.5 is out, but I should warn you that anything more complex than `String`,  `Number`, `Boolean`, or instances of classes is going to give you trouble.
