### ISSUE TITLE
Upgrade documentation to vue 2.5

### ISSUE THREAD

**Issue by KokoDoko** [Microsoft/TypeScript-Vue-Starter#27]
It seems a lot has changed in Vue 2.5 regarding typescript (and using `vue-class-component`). It would be helpful if the Typescript Vue starter can be updated. The example code repository is 2 years old! It contradicts the official Vue docs.

**Comment by windhc** [comment]
Upgrade  to vue 2.5 was good

**Comment by guyulmaz** [comment]
yes microsoft should up to date the starter kit with latest vue 2.5 improvements on typescript

**Comment by DanielRosenwasser** [comment]
Should be fixed by #5.
