### ISSUE TITLE
Fork of vue with special type declarations still necessary?

### ISSUE THREAD

**Issue by somombo** [Microsoft/TypeScript-Vue-Starter#32]
In `Readme.md`, is the following line from the instructions still necessary:
```
npm install https://github.com/DanielRosenwasser/vue#540a38fb21adb7a7bc394c65e23e6cffb36cd867
```

Or can we simply:
```
npm install vue
```

Thanks

**Comment by alexaandru** [comment]
I'm curious about this as well. I for one haven't used it and the example still worked fine, including type checking. Open for example `src/index.ts` and try adding a bogus method, `foobar()` or whatever and it will complain about it with:

> Object literal may only specify known properties, and 'foobar' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.

So I guess it's no longer needed... ?

**Comment by mkotlikov** [comment]
https://github.com/Microsoft/TypeScript-Vue-Starter/pull/34

**Comment by cyberhck** [comment]
#34 is closed and this issue can be closed, please do so.
