### ISSUE TITLE
Not able to use decorators to define a component

### ISSUE THREAD

**Issue by mansur786ali** [Microsoft/TypeScript-Vue-Starter#35]
Was giving a try for https://github.com/Microsoft/TypeScript-Vue-Starter#using-decorators-to-define-a-component

I see error:

TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type '<VC extends VueClass<{}>>(target: VC) => VC' is not assignable to type 'typeof HelloDecorator'.
    Property 'extend' is missing in type '<VC extends VueClass<{}>>(target: VC) => VC'.

I am using Typescript version: 2.7.1

//Hello.vue
<img width="489" alt="screen shot 2018-02-10 at 2 45 58 pm" src="https://user-images.githubusercontent.com/14272633/36060849-768690a8-0e77-11e8-97aa-223e18af596f.png">

// tsconfig.json
<img width="363" alt="screen shot 2018-02-10 at 3 30 03 pm" src="https://user-images.githubusercontent.com/14272633/36060850-76b758dc-0e77-11e8-85e5-71fb1fa42cc6.png">

**Comment by pboymt** [comment]
I had same problem

**Comment by hbelitzisap** [comment]
I also ran into the same error with TypeScript 2.7.1

**Comment by elevatebart** [comment]
How about importing Vue from vue ?
``` typescript
import Vue from 'vue';
```

**Comment by houguanghui** [comment]
[https://blog.csdn.net/wangy417/article/details/82014272](url)
