### ISSUE TITLE
why not do a typescript vue-cli?

### ISSUE THREAD

**Issue by cdllqos** [Microsoft/TypeScript-Vue-Starter#6]

**Comment by DanielRosenwasser** [comment]
Time constraints, and we're working with .d.ts files that are not in the main repo. Maybe we can work with @yyx990803 down the line though.

**Comment by cdllqos** [comment]
It's great to hear that. I think it can help developer   work more faster and efficienter.

**Comment by octref** [comment]
@zigomir has done some work: https://github.com/zigomir/typed-vue

**Comment by cdllqos** [comment]
@octref Thanks with that, I'll try it :)

**Comment by DanielRosenwasser** [comment]
You can track this at https://github.com/vuejs/vue-cli/issues/263.
