### ISSUE TITLE
application dont execute on "npm run serve"

### ISSUE THREAD

**Issue by skatesham** [Microsoft/TypeScript-Vue-Starter#68]
$ npm run serve
npm ERR! missing script: serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shan/.npm/_logs/2018-11-27T17_01_56_066Z-debug.log

**Comment by skatesham** [comment]
My bad

**Comment by skatesham** [comment]
I thoght that it was an aplication, but it is an module

**Comment by Anita-joseph** [comment]
![image](https://user-images.githubusercontent.com/51337302/60667278-6ed94c00-9e69-11e9-9170-a566cd73e8d5.png)

i am getting this error from 
npm init
