### ISSUE TITLE
Is there any tool like "create-react-app" with vue?

### ISSUE THREAD

**Issue by evont** [Microsoft/TypeScript-Vue-Starter#7]
maybe just something like create-react-app my-app --scripts-version=react-scripts-ts

**Comment by DanielRosenwasser** [comment]
There is the Vue CLI which we might look into using for this guide down the line, but in the mean time this solution can give a decent experience with the .d.ts files I put together.

**Comment by egoist** [comment]
There is [create-vue-app](https://github.com/egoist/create-vue-app), looking forward to adding typescript support at some point too.

**Comment by JonathanMH** [comment]
I think the officially recommended way is to specify a template and use vue-cli: https://github.com/vuejs-templates/webpack

So if one was to create a template that uses typescript, that would be a good idea I guess.

**Comment by DanielRosenwasser** [comment]
Track this at https://github.com/vuejs/vue-cli/issues/263
