### ISSUE TITLE
Getting IntelliSense from props

### ISSUE THREAD

**Issue by Outpox** [Microsoft/TypeScript-Vue-Starter#8]
Hello,
I've been struggling with getting completion on props given by a parent component in .vue files.

```vue
<template>
    <div>
        {{myClass}}
    </div>
</template>

<script lang="ts">
import Vue from "vue";
import { TestClass } from '../types/TestClass'; // TestClass interface in a .d.ts

export default Vue.extend({
    props: ['testClass'],
    mounted() {
        console.log(this.testClass);
    }
});
</script>
```
My goal is to have autocompletion inside the template on the `myClass` object of type `TestClass`.  So I'm trying to find a way to type my variable.  

Here's what I've tried until now:  

Using a computed property which return the type I want. **No IntelliSense.**
```js
export default Vue.extend({
    computed: {
        myClass(): TestClass {
            return this.testClass;
        }
    }
)}
```  
![image](https://cloud.githubusercontent.com/assets/3439246/26028236/be6640d0-381c-11e7-854a-f23cbdd4b8c5.png)
  
Creating a new variable in data which copy the initial value. **No IntelliSense.**
```js
export default Vue.extend({
    data() {
        return {
            myClass: <TestClass> this.testClass
        }
    }
)}
```  
  
Change props declaration to be able to specify the type.
`error TS2693: 'TestClass' only refers to a type, but is being used as a value here.`
```js
export default Vue.extend({
    props: {
        testClass: TestClass
    },
)}
```  
Obviously the same error when trying to set the `type` property
```js
export default Vue.extend({
    props: {
        testClass: {
            type: TestClass
        }
    },
)}
```  
  
I feel like I'm just hitting a wall because this is not supported, which is kind of a bummer because I wanted the power of TypeScript combined with Vue.  
I may have missed something or I'm just doing it wrong, if anyone have an idea please share :)

**Comment by DanielRosenwasser** [comment]
Unfortunately this is expected at the moment. This is just something the Vetur plugin may not yet support. Our team is willing to help the community where we can, but it's definitely no small task. CCing @octref.

**Comment by Outpox** [comment]
Alright thanks for the quick answer, I can keep on working without worrying to much.  
Thanks for your work, there was really no struggle to setup my project by following your tutorial :+1:

**Comment by octref** [comment]
Working on it at https://github.com/octref/vetur/issues/145. Probably will take a while.

**Comment by Outpox** [comment]
Thanks @octref, I'm following the issue on your repo :)  

Should I close the issue?

**Comment by octref** [comment]
Yea you can close it since this is an editor support issue. Nothing this repo could do on its side.
