### ISSUE TITLE
props detection and data() constructor

### ISSUE THREAD

**Issue by Grafikart** [Microsoft/TypeScript-Vue-Starter#9]
I just cloned the repo but I got errors when calling a property or instance variable. This error happens on the code published at the moment (TodoMVC).

### With properties

```typescript
export default Vue.extend({
  props: ['itemsLeft', 'clearCompleted', 'currentView'],
  computed: {
    itemSingularOrPlural(): string {
      return this.itemsLeft === 1 ? 'item' : 'items';
    },
    // ....
  }
});
```

throws the error `Property 'itemsLeft' does not exist on type 'Vue'.`

### With data()

```typescript
export default {
  methods: {
    demo () {
      alert(this.msg)
    }
  },
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
```

throws a `Property 'msg' does not exist on type '{ demo(): void; }'.`

## Solution ? 

Typescript "expects" things to be declared correctly and doesn't like VueJS ways of doing things (I might be wrong about this assertion, feel free to correct me). 

When I tried to setup VueJS + Typescript I ended up using decorators like this one https://github.com/vuejs/vue-class-component. Maybe some decorators should be included with this starter ?

**Comment by octref** [comment]
Check if you have the right dependency (custom version of vue and vue-router).

Second import Vue and set language as `ts` like so:

![image](https://cloud.githubusercontent.com/assets/4033249/26034585/091402aa-388d-11e7-9c85-7a7ec96d9496.png)

**Comment by DanielRosenwasser** [comment]
As for your second issue (with `data`), ensure you're using `Vue.extend`.

**Comment by Grafikart** [comment]
@octref I used `npm install` instead of `yarn` and everything worked like a charm.
